apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: clinvar-vcf
  version: 0.1.0
  description: Compare VCF variants against ClinVar database and generate a filtered report of clinically significant variants.
  authors:
    - madhava@openmined.org
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: dynamic-nextflow
  inputs:
    - name: participants
      type: "List[Record{participant_id: String, vcf_file: File, vcf_index: File?}]"
      description: CSV/TSV with participant_id and VCF file paths.
      format:
        kind: csv
        mapping:
          participant_id: participant_id
          vcf_file: vcf_file
          vcf_index: vcf_index
    - name: clinvar_vcf
      type: File
      description: ClinVar VCF database file (gzipped).
      format:
        kind: vcf
    - name: clinvar_index
      type: File
      description: ClinVar VCF index file (.tbi).
      format:
        kind: tbi
  outputs:
    - name: clinvar_report
      type: File
      description: TSV report of clinically significant variants with web links.
      format:
        kind: tsv
      path: clinvar_report.tsv
    - name: matched_vcf
      type: File
      description: VCF containing variants found in ClinVar.
      format:
        kind: vcf
      path: clinvar_matched.vcf.gz
  parameters: []
