name: pipeline-filter-samples
author: madhava@openmined.org
workflow: workflow.nf
template: dynamic-nextflow
version: 0.1.0
assets:
- filter_samples.py
parameters:
- name: extension
  type: String
  description: File extension to retain (e.g., .txt, .tsv)
  default: .txt
inputs:
- name: samplesheet
  type: File
  description: Samplesheet CSV listing per-participant file paths
  format: csv
outputs:
- name: filtered_sheet
  type: File
  description: Samplesheet filtered to rows matching the extension
  format: csv
  path: filtered_samplesheet.csv
