apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: haplo-y
  version: 0.1.0
  description: Analyze Y chromosome haplogroups from CRAM/BAM.
  authors:
    - madhava@openmined.org
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: dynamic-nextflow
  assets:
    - path: interpret_y_haplogroup.py
    - path: y_haplogroup_panel.GRCh38.tsv
    - path: y_haplogroup_panel.GRCh37.tsv
  inputs:
    - name: participants
      type: "List[Record{participant_id: String, aligned_file: File, aligned_index: File, reference_file: File, reference_index: File, ref_version: String?}]"
      description: CSV/TSV with participant_id, aligned/reference paths, and ref_version.
      format:
        kind: csv
        mapping:
          participant_id: participant_id
          aligned_file: aligned_file
          aligned_index: aligned_index
          reference_file: reference_file
          reference_index: reference_index
          ref_version: ref_version
  outputs:
    - name: haplogroup_report
      type: File
      description: Haplogroup report text.
      format:
        kind: txt
      path: report.txt
    - name: haplogroup_calls
      type: File
      description: Per-locus calls table.
      format:
        kind: tsv
      path: calls.tsv
  parameters: []
