apiVersion: syftbox.openmined.org/v1alpha1
kind: Flow
metadata:
  name: red-hair
  version: 0.1.0
spec:
  inputs:
    samplesheet:
      type: "List[Record{participant_id: String, aligned_file: File, aligned_index: File, reference_file: File, reference_index: File, ref_version: String?}]"
  steps:
    - id: red_hair
      uses:
        source:
          kind: local
          path: ./
      with:
        participants: inputs.samplesheet
      publish:
        red_hair_report: File(red_hair.txt)
