apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: red-hair
  version: 0.1.0
  description: Predict red hair trait from MC1R rs1805007.
  authors:
    - madhava@openmined.org
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: dynamic-nextflow
  assets:
    - path: red_hair.py
  inputs:
    - name: participants
      type: "List[Record{participant_id: String, aligned_file: File, aligned_index: File, reference_file: File, reference_index: File, ref_version: String?}]"
      description: CSV/TSV with participant_id, aligned/reference paths, and ref_version.
      format:
        kind: csv
        mapping:
          participant_id: participant_id
          aligned_file: aligned_file
          aligned_index: aligned_index
          reference_file: reference_file
          reference_index: reference_index
          ref_version: ref_version
  outputs:
    - name: red_hair_report
      type: File
      description: Red hair interpretation text.
      format:
        kind: txt
      path: red_hair.txt
  parameters: []
