required:
  - participant_id
  - genotype_file_path

rename:
  geno_path: genotype_file_path

defaults:
  age: 40

types:
  participant_id: string
  genotype_file_path: path
  weight: float
  height: float
  age: int
