name: apol1-bs
author: madhava@openmined.org
workflow: workflow.nf
template: sheet
assets:
  - schema.yaml
  - bs_classifier.py
  - bioscript/classifier.py
  - bioscript/reader.py
  - bioscript/types.py
