apiVersion: syftbox.openmined.org/v1alpha1
kind: Flow
metadata:
  name: eye-color
  version: 0.1.0
spec:
  inputs:
    samplesheet:
      type: "List[Record{participant_id: String, aligned_file: File, aligned_index: File, reference_file: File, reference_index: File, ref_version: String?}]"
  steps:
    - id: eye_color
      uses:
        source:
          kind: local
          path: ./
      with:
        participants: inputs.samplesheet
      publish:
        eye_color_report: File(eye_color.txt)
