apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: apol1-sheet
  version: 0.1.0
  authors:
    - madhava@openmined.org
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: sheet
  assets:
    - path: schema.yaml
    - path: apol1_classifier.py
  inputs: []
  outputs: []
  parameters: []
