apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: secure-aggregate
  version: 0.2.0
  description: Secure multi-party aggregation using Syqure SMPC (additive secret sharing + secure division)
spec:
  runner:
    runtime: syqure
    entrypoint: secure_aggregate.codon
    syqure:
      transport: hotlink
      skip_mhe_setup: true
  assets:
    - path: secure_aggregate.codon
  inputs:
    - name: counts
      type: File
      format: { kind: json }
      description: Aligned count array (clients only - stays private for MPC)
    - name: array_length
      type: String
      description: Number of elements to aggregate (from build_master)
  outputs:
    - name: aggregated_counts
      type: File
      format: { kind: json }
      path: aggregated_counts.json
      optional: true
      description: Aggregated allele frequencies (clients only; dealer does not emit)
