name: BioVault Integration Test - Local

on:
  schedule:
    # Run nightly at 2:30 AM UTC (30 minutes after docker tests)
    - cron: '30 2 * * *'
  workflow_dispatch:
    inputs:
      cleanup_after_success:
        description: 'Clean up resources after successful tests'
        type: boolean
        required: false
        default: true
      update_submodules:
        description: 'Update submodules to latest versions'
        type: boolean
        required: false
        default: true

jobs:
  test-with-local:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Update submodules to latest
      if: github.event_name == 'schedule' || github.event.inputs.update_submodules == 'true'
      run: |
        echo "Updating submodules to latest versions..."
        chmod +x submodules.sh
        ./submodules.sh --latest

    - name: Install just
      uses: extractions/setup-just@v1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: Build SyftBox from source
      run: |
        echo "Building SyftBox from source..."
        cd syftbox
        pip install -e .

    - name: Add minio to /etc/hosts
      run: |
        echo "127.0.0.1 minio" | sudo tee -a /etc/hosts
        cat /etc/hosts | grep minio

    - name: Run integration tests with local clients
      run: |
        # Export CI environment variable so the justfile knows we're in CI
        export CI=true
        if [ "${{ github.event.inputs.cleanup_after_success }}" = "false" ]; then
          just test-integration-local false
        else
          just test-integration-local
        fi

    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Server Logs ==="
        docker logs syftbox-server || true
        echo "=== Client 1 Directory ==="
        ls -la test-clients-local/client1@syftbox.net/ || true
        ls -la test-clients-local/client1@syftbox.net/.syftbox/ || true
        echo "=== Client 1 Logs ==="
        cat test-clients-local/client1@syftbox.net/.syftbox/logs/client.log || echo "No client1 log file found"
        echo "=== Client 2 Directory ==="
        ls -la test-clients-local/client2@syftbox.net/ || true
        ls -la test-clients-local/client2@syftbox.net/.syftbox/ || true
        echo "=== Client 2 Logs ==="
        cat test-clients-local/client2@syftbox.net/.syftbox/logs/client.log || echo "No client2 log file found"
        echo "=== Test files ==="
        ls -la test-clients-local/ || true
        echo "=== Check syftbox installation ==="
        which syftbox || echo "syftbox not in PATH"
        echo "=== Python packages ==="
        pip list | grep -i syft || true

    # Cleanup is handled by the just command based on test results