name: BioVault Integration Test

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      run_with_containers:
        description: 'Run tests with containerized clients'
        type: boolean
        required: false
        default: true
      run_with_local:
        description: 'Run tests with local clients (not implemented yet)'
        type: boolean
        required: false
        default: false

jobs:
  test-with-containers:
    runs-on: ubuntu-latest
    # Only run if containers checkbox is selected (or scheduled/default)
    if: github.event_name == 'schedule' || github.event.inputs.run_with_containers == 'true'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install just
      uses: extractions/setup-just@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: Add minio to /etc/hosts
      run: |
        echo "127.0.0.1 minio" | sudo tee -a /etc/hosts
        cat /etc/hosts | grep minio

    - name: Run integration tests with Docker
      run: just test-integration-docker

    - name: Show server logs on failure
      if: failure()
      run: |
        echo "=== Server Logs ==="
        docker logs syftbox-server || true
        echo "=== Client 1 Logs ==="
        docker logs syftbox-client-client1-syftbox-net || true
        echo "=== Client 2 Logs ==="
        docker logs syftbox-client-client2-syftbox-net || true

    # Cleanup is handled by the just command based on test results