name: Development Colab Test

on:
  # Allow manual trigger for testing
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-colab-test:
    name: Run Colab Test
    uses: ./.github/workflows/reusable-colab-test.yml
    with:
      event_name: ${{ github.event_name }}
      release_tag: ''
